# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Deploy Import
      inputs:
        containerRegistry: 'docker.io/addyjj'
        repository: 'addyjj/weather-import'
        command: 'buildAndPush'
        Dockerfile: 'Weather.Console/Dockerfile'
        tags: "latest"
        buildContext: "."
    - task: Docker@2
      displayName: Deploy Api
      inputs:
        containerRegistry: 'docker.io/addyjj'
        repository: 'addyjj/weather-api'
        command: 'buildAndPush'
        Dockerfile: 'Weather.WebApi/Dockerfile'
        tags: "latest"
        buildContext: "."